const modal=document.getElementById('modal'), content=document.getElementById('modalContent');
const tokenKey='ncc_token';
function openModal(type){modal.classList.add('show'); if(type==='register') registerForm(); if(type==='login') loginForm(); if(type==='admin') adminForm();}
function closeModal(){modal.classList.remove('show');}
function msg(t){return `<div class="notice">${t}</div>`}
function registerForm(){content.innerHTML=`<h2>Create your New Car Care account</h2><p>New customer? Register once and your service history will stay linked to your account.</p><form class="form" onsubmit="register(event)">
<input name="name" placeholder="Full name" required><input name="phone" placeholder="Mobile number" required><input name="email" type="email" placeholder="Email (optional)">
<input name="password" type="password" placeholder="Create password (6+ characters)" required><input name="carBrand" placeholder="Car brand"><input name="carModel" placeholder="Car model"><input name="carNumber" placeholder="Car registration number">
<button class="primary">Create Account</button></form><p>Already registered? <a href="#" onclick="loginForm();return false">Login</a></p>`}
async function register(e){e.preventDefault();const o=Object.fromEntries(new FormData(e));const r=await api('/api/register','POST',o);if(r.error)return content.innerHTML=msg(r.error)+content.innerHTML;localStorage.setItem(tokenKey,r.token);loadCustomer();}
function loginForm(){content.innerHTML=`<h2>Customer Login</h2><p>Use your registered mobile number.</p><form class="form" onsubmit="login(event)"><input name="phone" placeholder="Mobile number" required><input name="password" type="password" placeholder="Password" required><button class="primary">Login</button></form><p>New customer? <a href="#" onclick="registerForm();return false">Create account</a></p>`}
async function login(e){e.preventDefault();const o=Object.fromEntries(new FormData(e));const r=await api('/api/login','POST',o);if(r.error)return content.innerHTML=msg('<span class="error">'+r.error+'</span>')+content.innerHTML;localStorage.setItem(tokenKey,r.token);loadCustomer();}
function adminForm(){content.innerHTML=`<h2>Workshop Admin</h2><div class="notice">For workshop staff only.</div><form class="form" onsubmit="adminLogin(event)"><input name="email" type="email" placeholder="Admin email" required><input name="password" type="password" placeholder="Password" required><button class="primary">Open Admin Dashboard</button></form>`}
async function adminLogin(e){e.preventDefault();const o=Object.fromEntries(new FormData(e));const r=await api('/api/admin/login','POST',o);if(r.error)return content.innerHTML=msg('<span class="error">'+r.error+'</span>')+content.innerHTML;localStorage.setItem(tokenKey,r.token);loadAdmin();}
async function api(url,method='GET',body){const opts={method,headers:{'Content-Type':'application/json'}};if(localStorage.getItem(tokenKey))opts.headers.Authorization='Bearer '+localStorage.getItem(tokenKey);if(body)opts.body=JSON.stringify(body);const r=await fetch(url,opts);return r.json();}
async function loadCustomer(){const r=await api('/api/me');if(r.error){loginForm();return}content.innerHTML=`<div class="dashhead"><div><p class="eyebrow">CUSTOMER DASHBOARD</p><h2>Welcome, ${esc(r.customer.name)}</h2></div><button class="ghost" onclick="logout()">Logout</button></div>
<div class="notice">${esc(r.customer.car_brand||'Car')} ${esc(r.customer.car_model||'')} • ${esc(r.customer.car_number||'Registration not added')}</div>
<div class="dashstats"><div><b>${r.stats.visits}</b><small>Total Services</small></div><div><b>${r.stats.lastService||'—'}</b><small>Last Service</small></div><div><b>${new Date(r.customer.joined_at).toLocaleDateString()}</b><small>Joined New Car Care</small></div></div>
<h3>Service History</h3>${serviceTable(r.services)}<button class="primary" onclick="closeModal();location.hash='home'">Back to Website</button>`;modal.classList.add('show')}
function serviceTable(rows){if(!rows.length)return msg('No service records yet. Your workshop can add them after your visit.');return `<div class="tablewrap"><table class="table"><tr><th>Date</th><th>Service</th><th>KM</th><th>Next KM</th><th>Amount</th><th>Bill</th><th>Status</th><th>Payment</th><th>Notes</th></tr>${rows.map(x=>`<tr><td>${esc(x.service_date)}</td><td>${esc(x.service_type)}</td><td>${x.current_km?x.current_km+' KM':'—'}</td><td>${x.next_service_km?x.next_service_km+' KM':'—'}</td><td>₹ ${Number(x.amount).toLocaleString('en-IN')}</td><td>${esc(x.bill_no||'—')}</td><td>${esc(x.status||'—')}</td><td>${esc(x.payment_status||'—')}</td><td>${esc(x.notes||'—')}</td></tr>`).join('')}</table></div>`}
async function loadAdmin(){const r=await api('/api/admin/customers');if(r.error){adminForm();return}const st=await api('/api/admin/stats'); content.innerHTML=`<div class="dashhead"><div><p class="eyebrow">WORKSHOP CONTROL</p><h2>Customer Management</h2></div><button class="ghost" onclick="logout()">Logout</button></div><div class="dashstats"><div><b>${st.totalCustomers}</b><small>Customers</small></div><div><b>${st.totalServices}</b><small>Services</small></div><div><b>₹ ${Number(st.totalCollected).toLocaleString('en-IN')}</b><small>Paid</small></div></div><div class="notice">Every registered customer appears here so the workshop can follow up, review history and record completed services.</div><div class="tablewrap"><table class="table"><tr><th>Customer</th><th>Phone</th><th>Car</th><th>Visits</th><th>Last Service</th><th>Joined</th></tr>${r.map(x=>`<tr class="customer-row" onclick="adminCustomer(${x.id})"><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc((x.car_brand||'')+' '+(x.car_model||''))}</td><td>${x.visits}</td><td>${x.last_service||'—'}</td><td>${new Date(x.joined_at).toLocaleDateString()}</td></tr>`).join('')}</table></div>`;modal.classList.add('show')}
async function adminCustomer(id){const r=await api('/api/admin/customers/'+id);content.innerHTML=`<button class="ghost" onclick="loadAdmin()">← Customers</button><h2>${esc(r.customer.name)}</h2><div class="notice">📞 ${esc(r.customer.phone)} ${r.customer.email?' • ✉ '+esc(r.customer.email):''}<br>🚘 ${esc(r.customer.car_brand||'')} ${esc(r.customer.car_model||'')} • ${esc(r.customer.car_number||'')}</div><h3>Service History</h3>${serviceTable(r.services)}<h3>Add Service Record</h3><form class="form" onsubmit="addService(event,${id})"><input name="serviceDate" type="date" required><input name="serviceType" placeholder="Service type" required><input name="amount" type="number" min="0" placeholder="Amount (₹)"><input name="currentKm" type="number" min="0" placeholder="Current odometer KM"><input name="nextServiceKm" type="number" min="0" placeholder="Next service KM"><input name="estimateAmount" type="number" min="0" placeholder="Estimated amount (₹)"><select name="status"><option>RECEIVED</option><option>INSPECTION</option><option>WORK IN PROGRESS</option><option>READY</option><option>DELIVERED</option></select><select name="paymentStatus"><option>PAID</option><option>PENDING</option><option>PARTIAL</option></select><textarea name="notes" placeholder="Notes / work done"></textarea><button class="primary">Save Service</button></form>`}
async function addService(e,id){e.preventDefault();const o=Object.fromEntries(new FormData(e));o.customerId=id;const r=await api('/api/admin/services','POST',o);if(r.error)return alert(r.error);adminCustomer(id)}
function logout(){localStorage.removeItem(tokenKey);closeModal()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
